window.SAFE_UI={
brand:`<img src="assets/brand-mark.png" alt=""><span>Safe-Lier</span>`,
fields:`<div class="form-fields"><label>성함 *<input name="name" required autocomplete="name" placeholder="성함"></label><label>회사 / 기관<input name="company" autocomplete="organization" placeholder="회사 또는 기관명"></label><label class="full">이메일 *<input name="email" type="email" required autocomplete="email" placeholder="name@company.com"></label><label class="full">문의 유형<select name="type"><option>투자·제휴 문의</option><option>PoC·현장 실증 문의</option><option>기타 문의</option></select></label><label class="full">문의 내용 *<textarea name="message" required placeholder="협업 제안이나 현장 상황을 알려주세요."></textarea></label></div><p class="form-note">입력한 내용으로 이메일 초안을 엽니다. 서버에 저장하거나 자동 발송하지 않으며, 이메일 앱에서 직접 발송해 주세요.</p><button class="submit" type="submit">이메일로 문의 작성 <span>↗</span></button><p class="form-status" role="status"></p>`,
footer:`<p>세이플라이어 · 대표자 송경순 · 예비창업자(사업자 미등록)</p><p><a href="mailto:kaebbi@gmail.com">kaebbi@gmail.com</a> &nbsp; / &nbsp; <a href="tel:01026934295">010-2693-4295</a></p><small>© 2026 Safe-Lier. All rights reserved.</small>`,
init(theme){
document.body.insertAdjacentHTML('beforeend',`<aside class="review-bar" aria-label="시안 비교"><span>ROUND 02</span><a href="../index.html">비교 홈</a>${['a','b','c'].map(t=>`<a href="concept-${t}.html" class="${t===theme?'current':''}" ${t===theme?'aria-current="page"':''}>${t.toUpperCase()}안</a>`).join('')}<a href="requirements.html">문서 반영표 ↗</a></aside>`);
const btn=document.querySelector('.menu-button'), nav=document.querySelector('.nav-links');
if(btn&&nav){btn.addEventListener('click',()=>{const open=btn.getAttribute('aria-expanded')!=='true';btn.setAttribute('aria-expanded',String(open));nav.classList.toggle('open',open)});nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{btn.setAttribute('aria-expanded','false');nav.classList.remove('open')}))}
document.querySelectorAll('form').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();const d=new FormData(f);const subject=`[Safe-Lier] ${d.get('type')} / ${d.get('name')}`;const body=`성함: ${d.get('name')}\n회사 / 기관: ${d.get('company')}\n회신 이메일: ${d.get('email')}\n문의 유형: ${d.get('type')}\n\n${d.get('message')}`;location.href=`mailto:kaebbi@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`;f.querySelector('.form-status').textContent='이메일 앱에서 내용을 확인하고 발송해 주세요. 앱이 열리지 않으면 kaebbi@gmail.com으로 직접 보내주세요.'}));
}
};
