{
const d=SAFE_CONTENT,u=SAFE_UI;
document.getElementById('app').innerHTML=`<a class="skip-link" href="#main">본문으로 건너뛰기</a><header class="b-masthead"><a class="b-brand" href="#main">${u.brand}</a><span>사람을 향하는 기술.</span><nav class="nav-links" id="b-nav" aria-label="주요 메뉴"><a href="#problem">우리의 출발점</a><a href="#solution">안전의 방식</a><a href="#team">사람들</a><a href="#contact">함께하기 ↗</a></nav><button class="menu-button" aria-expanded="false" aria-controls="b-nav">목차 +</button></header>
<main id="main"><section class="b-cover"><img src="assets/worker.jpg" alt="센서를 착용한 산업현장 작업자 개발 개념 이미지"><div class="b-cover-top"><span>SAFE-LIER JOURNAL</span><span>01 — WORKER FIRST</span></div><div class="b-cover-copy"><span class="b-eyebrow">작업자를 지키는 AI 웨어러블 안전장치</span><h1>오늘도,<br>무사히.</h1><p>위험을 먼저 감지하고, 경고는 작업자에게 직접.<br>누구나 안전하게 일하고 돌아오는 내일을 위해.</p><a href="#problem" class="b-round-link">우리의 이야기 <span>↓</span></a></div><div class="b-cover-bottom"><span>시제품 / MVP 개발 중</span><span>제공 소개자료의 AI 생성 개발 개념 이미지</span></div></section>
<div class="b-running-line"><span>SAFETY FOLLOWS PEOPLE.</span><span>관제실보다 가까이. 작업자의 곁에.</span><span>SAFETY FOLLOWS PEOPLE.</span></div>
<section class="b-origin b-page" id="problem"><div class="b-section-marker"><span>01</span><span>THE STARTING POINT</span><span>현장에서 시작된 질문</span></div><div class="b-origin-grid"><aside><div class="b-side-number">5<span>명의 목소리에서<br>시작했습니다.</span></div><p>로버트보쉬코리아 세종공장<br>한솔제지 천안공장<br>HD현대인프라코어 인천공장</p><small>안전관리 담당자 심층 인터뷰 / 자체 조사<br>인터뷰 대상이며 확정 고객사·협력사가 아닙니다.</small></aside><div class="b-origin-copy"><h2>위험은 가까운데,<br><em>경고는 왜 멀리 있을까요.</em></h2><p class="b-lead">이동장비와 작업자의 동선이 겹치는 현장에서, 안전관리 담당자들은 더 가까운 경고가 필요하다고 말했습니다.</p>${d.issues.map((s,i)=>`<article class="b-problem-story"><span>0${i+1}</span><div><h3>${s.title}</h3><p>${s.text}</p></div></article>`).join('')}<details class="b-source"><summary>이 질문의 배경이 된 산업안전 통계 <span>↗</span></summary><div class="evidence-copy">${d.statistics}</div></details></div></div></section>
<section class="b-manifesto"><div class="b-page"><span class="b-eyebrow">OUR BELIEF</span><h2>안전은,<br>사람을 따라야 합니다<span>.</span></h2><div class="b-manifesto-foot"><span>Safely + -er</span><p>반딧불처럼 어둠 속을 밝히고,<br>위험한 순간 작업자를 지키는 세이플라이어.</p></div></div></section>
<section class="b-solution b-page" id="solution"><div class="b-section-marker"><span>02</span><span>SAFETY, CLOSER</span><span>사람에게 가까워지는 기술</span></div><div class="b-solution-title"><h2>감지하고.<br>판단하고.<br><em>바로 알리고.</em></h2><p>4방향 센서와 스마트폰 온디바이스 AI를 연결합니다. 관제실을 거치지 않고 작업자 주변에서 위험 감지부터 경고까지 수행하도록 개발합니다.</p></div><figure class="b-wide-figure"><img src="assets/detection.jpg" alt="4방향 센서로 접근하는 이동장비를 감지하고 스마트폰과 연동하는 개발 개념" loading="lazy"><figcaption>개발 개념 이미지 / 제공 소개자료의 AI 생성 이미지. 감지 성능과 경고 지연시간은 통제 시험·현장 실증으로 검증 예정.</figcaption></figure><div class="b-process"><div class="b-process-title"><span class="b-eyebrow">ON THE WORKER</span><h3>작업자에게 닿기까지,<br>다섯 번의 연결.</h3></div><ol>${d.steps.map((s,i)=>`<li><span>0${i+1}</span><div><h4>${s.title}</h4><p>${s.text}</p></div></li>`).join('')}</ol></div><div id="features" class="b-features"><div class="b-feature-number">360°<span>작업자를 중심으로.</span></div><dl>${d.features.map((f,i)=>`<div><dt><span>0${i+1}</span>${f.title}</dt><dd>${f.text}</dd></div>`).join('')}</dl></div><p class="b-target">제조·산업 사업장 / 중소 제조·50인 미만 사업장 / 안전관리자와 현장 작업자를 위해.</p><details class="b-source"><summary>공간·차량 중심의 안전 시스템과 비교하기 <span>↗</span></summary><div class="table-scroll">${d.comparison}</div><p class="note">${d.comparisonNote}</p></details></section>
<section class="b-people" id="team"><div class="b-page"><div class="b-section-marker"><span>03</span><span>THE PEOPLE</span><span>우리가 함께 만드는 이유</span></div><div class="b-people-heading"><h2>기술 뒤에는,<br><em>사람이 있습니다.</em></h2><p>임베디드 상용화 경험부터 최신 AI 연구까지.<br>각자의 전문성을 하나의 안전장치로 연결합니다.</p></div><div class="b-directory">${d.people.map((p,i)=>`<article>${p.image?`<img src="${p.image}" alt="${p.name}" loading="lazy">`:`<div class="b-person-letter" aria-hidden="true">0${i+1}</div>`}<div><span class="b-person-role">${p.role}</span><h3>${p.name}</h3><p>${p.bio}</p></div></article>`).join('')}</div><p class="note">${d.teamNote}</p></div></section>
<section class="b-roadmap b-page" id="progress"><div class="b-section-marker"><span>04</span><span>THE NEXT CHAPTER</span><span>앞으로의 6개월</span></div><div class="b-roadmap-layout"><div class="b-roadmap-heading"><h2>아이디어가<br>현장의 확신이<br><em>될 때까지.</em></h2><p>현재 시제품 / MVP 개발 중입니다.<br>6개월 내 기능 시제품 1세트와<br>후속 PoC 참여의향서 1부 확보가 목표입니다.</p></div><div>${d.milestones.map((s,i)=>`<article class="b-roadmap-entry"><span class="b-roadmap-month">${i*2+1}—${i*2+2}<small>개월 / 계획</small></span><h3>${s.title}</h3><p>${s.text}</p><p class="note">${s.criteria}</p></article>`).join('')}</div></div><div class="b-validation"><p>${d.validation}</p><p>${d.deliverables}</p></div></section>
<section class="b-partnership" id="pricing"><div class="b-page"><div class="b-section-marker"><span>05</span><span>WORK TOGETHER</span><span>현장으로 가는 방법</span></div><h2>한 사람부터.<br><em>한 현장씩.</em></h2><div class="b-offer"><p>작업자 1인 1세트.<br>센서 단말 4개와 앱·온디바이스 AI.<br>스마트폰은 고객 보유 기기를 활용합니다.</p><div><span>일시 구매 / 기획안</span><strong>199<small>만 원</small></strong><p>세트당 · 추가 약정 없음</p></div><div><span>월 구독 / 기획안</span><strong>7.6<small>만 원</small></strong><p>월·세트당 / 36개월 약정<br>유지관리 포함 · 총 273.6만 원</p></div></div><p class="note">부가세 별도. 최종 가격·사양·공급 조건은 확정 전입니다. 조끼 등 착용 구조는 현장 조건에 따라 협의합니다.</p><details class="b-source"><summary>도입 지원과 공급 방식에 관한 계획 <span>↗</span></summary><div class="evidence-copy">${d.support}</div></details><details class="b-source"><summary>투자·제휴를 위한 시장 규모와 가정 <span>↗</span></summary><div class="evidence-copy">${d.market}</div></details></div></section>
<section class="b-faq b-page" id="faq"><div class="b-section-marker"><span>06</span><span>IN CONVERSATION</span><span>궁금한 이야기</span></div><h2>당신의 질문에,<br><em>우리의 답.</em></h2><div class="b-qa">${d.faqs.map((f,i)=>`<article><div><span>Q.0${i+1}</span><h3>${f.q}</h3></div><p>${f.a}</p></article>`).join('')}</div></section>
<section class="b-contact" id="contact"><div class="b-page"><span class="b-eyebrow">LET’S TALK ABOUT TOMORROW</span><div class="b-contact-grid"><div><h2>함께 지킬<br>내일을<br><em>이야기해요.</em></h2><p>투자·제휴, PoC·현장 실증 문의</p><a class="b-mail" href="mailto:kaebbi@gmail.com">kaebbi@gmail.com ↗</a><a href="tel:01026934295">010-2693-4295</a></div><form>${u.fields}</form></div></div></section></main><footer class="b-footer"><a href="#main">Safe-Lier.</a><div>${u.footer}</div><span>오늘도, 무사히.</span></footer>`;
u.init('b');
}
