{
const d=SAFE_CONTENT,u=SAFE_UI;
document.getElementById('app').innerHTML=`<a class="skip-link" href="#main">본문으로 건너뛰기</a>
<header class="catalog-header"><a class="a-brand" href="#main">${u.brand}</a><nav class="nav-links" id="a-nav" aria-label="주요 메뉴"><a href="#features">제품 살펴보기</a><a href="#pricing">도입 구성</a><a href="#team">만드는 사람들</a></nav><a class="a-header-cta" href="#contact">함께하기 ↗</a><button class="menu-button" aria-expanded="false" aria-controls="a-nav">메뉴</button></header>
<main id="main"><section class="a-hero"><span class="a-kicker">INTRODUCING SAFE-LIER</span><h1>입는 순간부터,<br>안전의 중심은 당신.</h1><p>작업자 주변의 위험을 감지하고, 스마트폰 AI로 판단하고,<br>조끼의 LED와 경고음으로 직접 알리는 웨어러블 안전장치.</p><div class="a-hero-actions"><a class="a-pill" href="#features">제품 살펴보기 <span>↓</span></a><span class="a-status"><i></i> 시제품 / MVP 개발 중</span></div><figure class="a-product-stage"><span class="a-stage-tag">THE WEARABLE SAFETY SYSTEM</span><img src="assets/product-clean.jpg" alt="4개 센서가 장착된 안전조끼 앞면과 뒷면, 스마트폰의 개발 개념 이미지"><div class="a-callout left"><b>4 sensors.</b><span>전·후·좌·우 접근 감지</span></div><div class="a-callout right"><b>One smartphone.</b><span>고객 보유 스마트폰의 AI 활용</span></div><figcaption>제공 소개자료의 AI 생성 개발 개념 이미지 · 실제 제품 사양은 변경될 수 있습니다.</figcaption></figure></section>
<section class="a-features a-container" id="features"><div class="a-center"><span class="a-kicker">SMALL SYSTEM. CLOSER SAFETY.</span><h2>네 가지 기능.<br>하나의 안전한 흐름.</h2></div><div class="a-bento"><article class="a-feature-360"><span class="a-label">01 / SENSE</span><div class="a-big-number">360<span>°</span></div><h3>${d.features[0].title}</h3><p>${d.features[0].text}</p><img src="assets/prototype.jpg" alt="작업자 주변 4방향 감지 개발 개념" loading="lazy"><small>AI 생성 개발 개념 이미지</small></article><article class="a-feature-ai"><span class="a-label">02 / UNDERSTAND</span><div class="a-phone" aria-hidden="true"><span class="a-phone-camera"></span><span class="a-ai-word">AI<span>ON YOUR DEVICE</span></span><i></i></div><h3>${d.features[1].title}</h3><p>${d.features[1].text}</p></article><article class="a-feature-alert"><div><span class="a-label">03 / ALERT</span><h3>빛과 소리로,<br>작업자에게 바로.</h3><p>${d.features[2].text}</p></div><div class="a-alert-art" aria-hidden="true"><i></i><i></i><i></i><span>LED<br>+ SOUND</span></div></article><article class="a-feature-connect"><span class="a-label">04 / CONNECT</span><h3>별도의 현장 인프라<br>추가 설치 없이.</h3><p>${d.features[3].text}</p><div class="a-connect-words"><b>조끼 착용</b><span>+</span><b>스마트폰 연결</b></div></article></div><p class="note a-disclaimer">각 기능은 개발 목표입니다. 감지 성능·경고 지연시간·경고 인지율은 통제 시험과 현장 실증으로 검증할 예정입니다.</p></section>
<section class="a-how" id="solution"><div class="a-container"><div class="a-center"><span class="a-kicker">FROM SENSOR TO WORKER</span><h2>입고, 연결하면.<br>감지에서 경고까지.</h2></div><div class="a-five-steps">${d.steps.map((s,i)=>`<article><span class="a-step-dot">${i+1}</span><h3>${s.title}</h3><p>${s.text}</p></article>`).join('')}</div></div></section>
<section class="a-context a-container" id="problem"><div class="a-context-heading"><span class="a-kicker">DESIGNED FOR REAL WORKPLACES</span><h2>작업자의 움직임에<br>안전이 함께하도록.</h2><p>제조·산업 사업장, 특히 안전 인프라 구축 부담이 큰 중소 제조·50인 미만 사업장을 위해 개발합니다.</p></div><div class="a-context-list">${d.issues.map((s,i)=>`<article><span>0${i+1}</span><div><h3>${s.title}</h3><p>${s.text}</p></div></article>`).join('')}</div><div class="a-interview"><strong>5명</strong><p>안전관리 담당자 심층 인터뷰 완료<br><small>로버트보쉬코리아 세종공장 · 한솔제지 천안공장 · HD현대인프라코어 인천공장 / 자체 조사<br>인터뷰 대상이며 확정 고객사·협력사가 아닙니다.</small></p></div><details class="a-fold"><summary>기존 시스템과 어떻게 다른가요? <span>+</span></summary><div class="table-scroll">${d.comparison}</div><p class="note">${d.comparisonNote}</p></details><details class="a-fold"><summary>개발 배경이 된 산업안전 통계 <span>+</span></summary><div class="evidence-copy">${d.statistics}</div></details></section>
<section class="a-pricing" id="pricing"><div class="a-container"><div class="a-center"><span class="a-kicker">ONE WORKER. ONE SET.</span><h2>한 사람을 위한<br>하나의 세트.</h2><p>센서 단말 4개 + 스마트폰 앱·온디바이스 AI<br>스마트폰은 고객 보유 기기를 활용합니다.</p></div><div class="a-purchase"><figure><img src="assets/product.jpg" alt="전면 센서 2개와 후면 센서 2개 및 스마트폰 앱의 구성 예시" loading="lazy"><figcaption class="source-label">AI 생성 구성 예시 · 조끼 등 착용 구조는 현장 조건에 따라 협의</figcaption></figure><div class="a-purchase-options"><div class="a-switch" role="group" aria-label="도입 방식"><button aria-pressed="true" data-price="buy">일시 구매</button><button aria-pressed="false" data-price="subscribe">월 구독</button></div><span class="a-label">예상 도입 비용 · 기획안</span><div class="a-price-value"><b id="a-price">199</b><span id="a-price-unit">만 원 / 세트</span></div><p id="a-price-detail">추가 약정 없음 · 부가세 별도</p><a class="a-pill" href="#contact">도입·실증 상담하기 ↗</a><p class="note">구매 199만 원 / 월 구독 7.6만 원<br>구독은 36개월 약정·유지관리 포함, 총 273.6만 원.<br>가격·사양·공급 조건은 확정 전이며 부가세 별도입니다.</p></div></div><details class="a-fold"><summary>도입 지원과 공급 방식 <span>+</span></summary><div class="evidence-copy">${d.support}</div></details></div></section>
<section class="a-progress a-container" id="progress"><div class="a-center"><span class="a-kicker">MADE TO BE PROVEN</span><h2>현장에서 확인할<br>다음 6개월.</h2><p>기능 시제품 1세트, 후속 PoC 참여의향서 1부를 목표로.</p></div><div class="a-roadmap">${d.milestones.map((s,i)=>`<article><span>0${i*2+1}—0${i*2+2}<small>개월 / 계획</small></span><div><h3>${s.title}</h3><p>${s.text}</p><p class="note">${s.criteria}</p></div></article>`).join('')}</div><p class="note">${d.validation}</p><p class="a-deliverables">${d.deliverables}</p><details class="a-fold"><summary>투자·제휴를 위한 시장 가정 <span>+</span></summary><div class="evidence-copy">${d.market}</div></details></section>
<section class="a-people" id="team"><div class="a-container"><div class="a-center"><span class="a-kicker">MEET THE MAKERS</span><h2>작은 장치에 담긴<br>여섯 사람의 경험.</h2></div><div class="a-people-grid">${d.people.map((p,i)=>`<article>${p.image?`<img src="${p.image}" alt="${p.name}" loading="lazy">`:`<div class="a-monogram" aria-hidden="true">${p.name.slice(0,1)}<span>SAFE-LIER</span></div>`}<h3>${p.name}</h3><span>${p.role}</span><p>${p.bio}</p></article>`).join('')}</div><p class="note">${d.teamNote}</p></div></section>
<section class="a-faq" id="faq"><span class="a-kicker">A FEW MORE THINGS</span><h2>궁금한 점을<br>먼저 답합니다.</h2>${d.faqs.map(f=>`<details class="a-fold"><summary>${f.q}<span>+</span></summary><p>${f.a}</p></details>`).join('')}</section>
<section class="a-contact" id="contact"><span class="a-kicker">LET’S MAKE WORK SAFER</span><h2>안전의 다음 장을,<br>함께.</h2><a class="a-mail" href="mailto:kaebbi@gmail.com">kaebbi@gmail.com ↗</a><p>투자·제휴 · PoC·현장 실증 문의</p><form class="a-form">${u.fields}</form></section></main><footer class="a-footer"><a class="a-brand" href="#main">${u.brand}</a><div>${u.footer}</div><span>SAFELY + -ER<br>작업자를 지키는 웨어러블 안전장비</span></footer>`;
document.querySelectorAll('[data-price]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-price]').forEach(b=>b.setAttribute('aria-pressed',String(b===btn)));const buy=btn.dataset.price==='buy';document.querySelector('#a-price').textContent=buy?'199':'7.6';document.querySelector('#a-price-unit').textContent=buy?'만 원 / 세트':'만 원 / 월·세트';document.querySelector('#a-price-detail').textContent=buy?'추가 약정 없음 · 부가세 별도':'36개월 약정 · 유지관리 포함 · 부가세 별도'}));
u.init('a');
}
